### ISSUE TITLE
SHAKE is not returning to original screen position

### ISSUE THREAD

**Issue by flamendless** [SSYGEN/STALKER-X#3]
hi, after using the shake sample in the readme.md, the screen didnt return to its original position. What ive done is put a rectangle as the screen boundary, then after shaking, the rectangle screen boundary is offset now and that affects collision as well. 

PS, no follow or deadlock used.

**Comment by SSYGEN** [comment]
You need to tell the camera to follow the position you want it to follow and then it will go back there after the shake ends. The lerp value needs to be different than 1 otherwise a shake won't happen.
